alias "v = vim"
alias "nv=nvim"
alias "ls=eza --color=always --icons=always --hyperlink -F"
alias "s=kitten ssh"
alias "tree=eza -T"
alias "search-alias=alias | grep"
alias "se=sudoedit"
alias "ssa=sudo systemctl start"
alias "ssd=sudo systemctl disable"
alias "ssdr=sudo systemctl daemon-reload"
alias "sse=sudo systemctl enable --now"
alias "ssl=sudo systemctl reload"
alias "sso=sudo systemctl stop"
alias "ssr=sudo systemctl restart"
alias "sss=sudo systemctl status"
